name: web-CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          name: shop/front
          # The login username for the registry
          username: ${{secrets.DOCKER_USERNAME}}
          # The login password for the registry
          password: ${{secrets.DOCKER_PASSWORD}}
          # Use registry for pushing to a custom registry
          registry: ${{secrets.DOCKER_REGISTRY}}
          # Use dockerfile when you would like to explicitly build a Dockerfile
          dockerfile: /
          cache: true
